// Code generated by entc, DO NOT EDIT.

package wugong

import (
	"time"
)

const (
	// Label holds the string label denoting the wugong type in the database.
	Label = "wu_gong"
	// FieldID holds the string denoting the id field in the database.
	FieldID        = "id"         // FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt = "created_at" // FieldUpdatedAt holds the string denoting the updated_at vertex property in the database.
	FieldUpdatedAt = "updated_at" // FieldName holds the string denoting the name vertex property in the database.
	FieldName      = "name"       // FieldDamage holds the string denoting the damage vertex property in the database.
	FieldDamage    = "damage"     // FieldLevel holds the string denoting the level vertex property in the database.
	FieldLevel     = "level"

	// Table holds the table name of the wugong in the database.
	Table = "wu_gongs"
)

// Columns holds all SQL columns for wugong fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldDamage,
	FieldLevel,
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDamage holds the default value on creation for the damage field.
	DefaultDamage int
	// LevelValidator is a validator for the "level" field. It is called by the builders before save.
	LevelValidator func(uint8) error
)
