// Code generated by entc, DO NOT EDIT.

package menpai

import (
	"time"
)

const (
	// Label holds the string label denoting the menpai type in the database.
	Label = "men_pai"
	// FieldID holds the string denoting the id field in the database.
	FieldID        = "id"         // FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt = "created_at" // FieldUpdatedAt holds the string denoting the updated_at vertex property in the database.
	FieldUpdatedAt = "updated_at" // FieldName holds the string denoting the name vertex property in the database.
	FieldName      = "name"       // FieldAddress holds the string denoting the address vertex property in the database.
	FieldAddress   = "address"

	// EdgeDisciples holds the string denoting the disciples edge name in mutations.
	EdgeDisciples = "disciples"

	// Table holds the table name of the menpai in the database.
	Table = "men_pais"
	// DisciplesTable is the table the holds the disciples relation/edge.
	DisciplesTable = "jiang_hu_rens"
	// DisciplesInverseTable is the table name for the JiangHuRen entity.
	// It exists in this package in order to avoid circular dependency with the "jianghuren" package.
	DisciplesInverseTable = "jiang_hu_rens"
	// DisciplesColumn is the table column denoting the disciples relation/edge.
	DisciplesColumn = "men_pai_disciples"
)

// Columns holds all SQL columns for menpai fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldAddress,
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultAddress holds the default value on creation for the address field.
	DefaultAddress string
)
