// Code generated by entc, DO NOT EDIT.

package weapon

import (
	"time"
)

const (
	// Label holds the string label denoting the weapon type in the database.
	Label = "weapon"
	// FieldID holds the string denoting the id field in the database.
	FieldID        = "id"         // FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt = "created_at" // FieldUpdatedAt holds the string denoting the updated_at vertex property in the database.
	FieldUpdatedAt = "updated_at" // FieldName holds the string denoting the name vertex property in the database.
	FieldName      = "name"       // FieldLevel holds the string denoting the level vertex property in the database.
	FieldLevel     = "level"      // FieldCategory holds the string denoting the category vertex property in the database.
	FieldCategory  = "category"

	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"

	// Table holds the table name of the weapon in the database.
	Table = "weapons"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "weapons"
	// OwnerInverseTable is the table name for the JiangHuRen entity.
	// It exists in this package in order to avoid circular dependency with the "jianghuren" package.
	OwnerInverseTable = "jiang_hu_rens"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "jiang_hu_ren_weapon"
)

// Columns holds all SQL columns for weapon fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldLevel,
	FieldCategory,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Weapon type.
var ForeignKeys = []string{
	"jiang_hu_ren_weapon",
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultLevel holds the default value on creation for the level field.
	DefaultLevel int
	// DefaultCategory holds the default value on creation for the category field.
	DefaultCategory int
)
