// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/BiLuoHui/ganshijiumei/ent/migrate"

	"github.com/BiLuoHui/ganshijiumei/ent/jianghuren"
	"github.com/BiLuoHui/ganshijiumei/ent/menpai"
	"github.com/BiLuoHui/ganshijiumei/ent/weapon"
	"github.com/BiLuoHui/ganshijiumei/ent/wugong"

	"github.com/facebookincubator/ent/dialect"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// JiangHuRen is the client for interacting with the JiangHuRen builders.
	JiangHuRen *JiangHuRenClient
	// MenPai is the client for interacting with the MenPai builders.
	MenPai *MenPaiClient
	// Weapon is the client for interacting with the Weapon builders.
	Weapon *WeaponClient
	// WuGong is the client for interacting with the WuGong builders.
	WuGong *WuGongClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.JiangHuRen = NewJiangHuRenClient(c.config)
	c.MenPai = NewMenPaiClient(c.config)
	c.Weapon = NewWeaponClient(c.config)
	c.WuGong = NewWuGongClient(c.config)
}

// Open opens a connection to the database specified by the driver name and a
// driver-specific data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		config:     cfg,
		JiangHuRen: NewJiangHuRenClient(cfg),
		MenPai:     NewMenPaiClient(cfg),
		Weapon:     NewWeaponClient(cfg),
		WuGong:     NewWuGongClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		JiangHuRen.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.JiangHuRen.Use(hooks...)
	c.MenPai.Use(hooks...)
	c.Weapon.Use(hooks...)
	c.WuGong.Use(hooks...)
}

// JiangHuRenClient is a client for the JiangHuRen schema.
type JiangHuRenClient struct {
	config
}

// NewJiangHuRenClient returns a client for the JiangHuRen from the given config.
func NewJiangHuRenClient(c config) *JiangHuRenClient {
	return &JiangHuRenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `jianghuren.Hooks(f(g(h())))`.
func (c *JiangHuRenClient) Use(hooks ...Hook) {
	c.hooks.JiangHuRen = append(c.hooks.JiangHuRen, hooks...)
}

// Create returns a create builder for JiangHuRen.
func (c *JiangHuRenClient) Create() *JiangHuRenCreate {
	mutation := newJiangHuRenMutation(c.config, OpCreate)
	return &JiangHuRenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for JiangHuRen.
func (c *JiangHuRenClient) Update() *JiangHuRenUpdate {
	mutation := newJiangHuRenMutation(c.config, OpUpdate)
	return &JiangHuRenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *JiangHuRenClient) UpdateOne(jhr *JiangHuRen) *JiangHuRenUpdateOne {
	return c.UpdateOneID(jhr.ID)
}

// UpdateOneID returns an update builder for the given id.
func (c *JiangHuRenClient) UpdateOneID(id int) *JiangHuRenUpdateOne {
	mutation := newJiangHuRenMutation(c.config, OpUpdateOne)
	mutation.id = &id
	return &JiangHuRenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for JiangHuRen.
func (c *JiangHuRenClient) Delete() *JiangHuRenDelete {
	mutation := newJiangHuRenMutation(c.config, OpDelete)
	return &JiangHuRenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *JiangHuRenClient) DeleteOne(jhr *JiangHuRen) *JiangHuRenDeleteOne {
	return c.DeleteOneID(jhr.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *JiangHuRenClient) DeleteOneID(id int) *JiangHuRenDeleteOne {
	builder := c.Delete().Where(jianghuren.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &JiangHuRenDeleteOne{builder}
}

// Create returns a query builder for JiangHuRen.
func (c *JiangHuRenClient) Query() *JiangHuRenQuery {
	return &JiangHuRenQuery{config: c.config}
}

// Get returns a JiangHuRen entity by its id.
func (c *JiangHuRenClient) Get(ctx context.Context, id int) (*JiangHuRen, error) {
	return c.Query().Where(jianghuren.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *JiangHuRenClient) GetX(ctx context.Context, id int) *JiangHuRen {
	jhr, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return jhr
}

// QueryWeapon queries the weapon edge of a JiangHuRen.
func (c *JiangHuRenClient) QueryWeapon(jhr *JiangHuRen) *WeaponQuery {
	query := &WeaponQuery{config: c.config}
	id := jhr.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(jianghuren.Table, jianghuren.FieldID, id),
		sqlgraph.To(weapon.Table, weapon.FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, jianghuren.WeaponTable, jianghuren.WeaponColumn),
	)
	query.sql = sqlgraph.Neighbors(jhr.driver.Dialect(), step)

	return query
}

// QueryMenpai queries the menpai edge of a JiangHuRen.
func (c *JiangHuRenClient) QueryMenpai(jhr *JiangHuRen) *MenPaiQuery {
	query := &MenPaiQuery{config: c.config}
	id := jhr.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(jianghuren.Table, jianghuren.FieldID, id),
		sqlgraph.To(menpai.Table, menpai.FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, jianghuren.MenpaiTable, jianghuren.MenpaiColumn),
	)
	query.sql = sqlgraph.Neighbors(jhr.driver.Dialect(), step)

	return query
}

// QuerySpouse queries the spouse edge of a JiangHuRen.
func (c *JiangHuRenClient) QuerySpouse(jhr *JiangHuRen) *JiangHuRenQuery {
	query := &JiangHuRenQuery{config: c.config}
	id := jhr.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(jianghuren.Table, jianghuren.FieldID, id),
		sqlgraph.To(jianghuren.Table, jianghuren.FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, jianghuren.SpouseTable, jianghuren.SpouseColumn),
	)
	query.sql = sqlgraph.Neighbors(jhr.driver.Dialect(), step)

	return query
}

// QueryMaster queries the master edge of a JiangHuRen.
func (c *JiangHuRenClient) QueryMaster(jhr *JiangHuRen) *JiangHuRenQuery {
	query := &JiangHuRenQuery{config: c.config}
	id := jhr.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(jianghuren.Table, jianghuren.FieldID, id),
		sqlgraph.To(jianghuren.Table, jianghuren.FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, jianghuren.MasterTable, jianghuren.MasterColumn),
	)
	query.sql = sqlgraph.Neighbors(jhr.driver.Dialect(), step)

	return query
}

// QueryApprentices queries the apprentices edge of a JiangHuRen.
func (c *JiangHuRenClient) QueryApprentices(jhr *JiangHuRen) *JiangHuRenQuery {
	query := &JiangHuRenQuery{config: c.config}
	id := jhr.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(jianghuren.Table, jianghuren.FieldID, id),
		sqlgraph.To(jianghuren.Table, jianghuren.FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, jianghuren.ApprenticesTable, jianghuren.ApprenticesColumn),
	)
	query.sql = sqlgraph.Neighbors(jhr.driver.Dialect(), step)

	return query
}

// QueryFollowers queries the followers edge of a JiangHuRen.
func (c *JiangHuRenClient) QueryFollowers(jhr *JiangHuRen) *JiangHuRenQuery {
	query := &JiangHuRenQuery{config: c.config}
	id := jhr.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(jianghuren.Table, jianghuren.FieldID, id),
		sqlgraph.To(jianghuren.Table, jianghuren.FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, jianghuren.FollowersTable, jianghuren.FollowersPrimaryKey...),
	)
	query.sql = sqlgraph.Neighbors(jhr.driver.Dialect(), step)

	return query
}

// QueryFollowing queries the following edge of a JiangHuRen.
func (c *JiangHuRenClient) QueryFollowing(jhr *JiangHuRen) *JiangHuRenQuery {
	query := &JiangHuRenQuery{config: c.config}
	id := jhr.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(jianghuren.Table, jianghuren.FieldID, id),
		sqlgraph.To(jianghuren.Table, jianghuren.FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, jianghuren.FollowingTable, jianghuren.FollowingPrimaryKey...),
	)
	query.sql = sqlgraph.Neighbors(jhr.driver.Dialect(), step)

	return query
}

// QueryFriends queries the friends edge of a JiangHuRen.
func (c *JiangHuRenClient) QueryFriends(jhr *JiangHuRen) *JiangHuRenQuery {
	query := &JiangHuRenQuery{config: c.config}
	id := jhr.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(jianghuren.Table, jianghuren.FieldID, id),
		sqlgraph.To(jianghuren.Table, jianghuren.FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, jianghuren.FriendsTable, jianghuren.FriendsPrimaryKey...),
	)
	query.sql = sqlgraph.Neighbors(jhr.driver.Dialect(), step)

	return query
}

// Hooks returns the client hooks.
func (c *JiangHuRenClient) Hooks() []Hook {
	return c.hooks.JiangHuRen
}

// MenPaiClient is a client for the MenPai schema.
type MenPaiClient struct {
	config
}

// NewMenPaiClient returns a client for the MenPai from the given config.
func NewMenPaiClient(c config) *MenPaiClient {
	return &MenPaiClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `menpai.Hooks(f(g(h())))`.
func (c *MenPaiClient) Use(hooks ...Hook) {
	c.hooks.MenPai = append(c.hooks.MenPai, hooks...)
}

// Create returns a create builder for MenPai.
func (c *MenPaiClient) Create() *MenPaiCreate {
	mutation := newMenPaiMutation(c.config, OpCreate)
	return &MenPaiCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for MenPai.
func (c *MenPaiClient) Update() *MenPaiUpdate {
	mutation := newMenPaiMutation(c.config, OpUpdate)
	return &MenPaiUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MenPaiClient) UpdateOne(mp *MenPai) *MenPaiUpdateOne {
	return c.UpdateOneID(mp.ID)
}

// UpdateOneID returns an update builder for the given id.
func (c *MenPaiClient) UpdateOneID(id int) *MenPaiUpdateOne {
	mutation := newMenPaiMutation(c.config, OpUpdateOne)
	mutation.id = &id
	return &MenPaiUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MenPai.
func (c *MenPaiClient) Delete() *MenPaiDelete {
	mutation := newMenPaiMutation(c.config, OpDelete)
	return &MenPaiDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *MenPaiClient) DeleteOne(mp *MenPai) *MenPaiDeleteOne {
	return c.DeleteOneID(mp.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *MenPaiClient) DeleteOneID(id int) *MenPaiDeleteOne {
	builder := c.Delete().Where(menpai.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MenPaiDeleteOne{builder}
}

// Create returns a query builder for MenPai.
func (c *MenPaiClient) Query() *MenPaiQuery {
	return &MenPaiQuery{config: c.config}
}

// Get returns a MenPai entity by its id.
func (c *MenPaiClient) Get(ctx context.Context, id int) (*MenPai, error) {
	return c.Query().Where(menpai.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MenPaiClient) GetX(ctx context.Context, id int) *MenPai {
	mp, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return mp
}

// QueryDisciples queries the disciples edge of a MenPai.
func (c *MenPaiClient) QueryDisciples(mp *MenPai) *JiangHuRenQuery {
	query := &JiangHuRenQuery{config: c.config}
	id := mp.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(menpai.Table, menpai.FieldID, id),
		sqlgraph.To(jianghuren.Table, jianghuren.FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, menpai.DisciplesTable, menpai.DisciplesColumn),
	)
	query.sql = sqlgraph.Neighbors(mp.driver.Dialect(), step)

	return query
}

// Hooks returns the client hooks.
func (c *MenPaiClient) Hooks() []Hook {
	return c.hooks.MenPai
}

// WeaponClient is a client for the Weapon schema.
type WeaponClient struct {
	config
}

// NewWeaponClient returns a client for the Weapon from the given config.
func NewWeaponClient(c config) *WeaponClient {
	return &WeaponClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `weapon.Hooks(f(g(h())))`.
func (c *WeaponClient) Use(hooks ...Hook) {
	c.hooks.Weapon = append(c.hooks.Weapon, hooks...)
}

// Create returns a create builder for Weapon.
func (c *WeaponClient) Create() *WeaponCreate {
	mutation := newWeaponMutation(c.config, OpCreate)
	return &WeaponCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Weapon.
func (c *WeaponClient) Update() *WeaponUpdate {
	mutation := newWeaponMutation(c.config, OpUpdate)
	return &WeaponUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WeaponClient) UpdateOne(w *Weapon) *WeaponUpdateOne {
	return c.UpdateOneID(w.ID)
}

// UpdateOneID returns an update builder for the given id.
func (c *WeaponClient) UpdateOneID(id int) *WeaponUpdateOne {
	mutation := newWeaponMutation(c.config, OpUpdateOne)
	mutation.id = &id
	return &WeaponUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Weapon.
func (c *WeaponClient) Delete() *WeaponDelete {
	mutation := newWeaponMutation(c.config, OpDelete)
	return &WeaponDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *WeaponClient) DeleteOne(w *Weapon) *WeaponDeleteOne {
	return c.DeleteOneID(w.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *WeaponClient) DeleteOneID(id int) *WeaponDeleteOne {
	builder := c.Delete().Where(weapon.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WeaponDeleteOne{builder}
}

// Create returns a query builder for Weapon.
func (c *WeaponClient) Query() *WeaponQuery {
	return &WeaponQuery{config: c.config}
}

// Get returns a Weapon entity by its id.
func (c *WeaponClient) Get(ctx context.Context, id int) (*Weapon, error) {
	return c.Query().Where(weapon.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WeaponClient) GetX(ctx context.Context, id int) *Weapon {
	w, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return w
}

// QueryOwner queries the owner edge of a Weapon.
func (c *WeaponClient) QueryOwner(w *Weapon) *JiangHuRenQuery {
	query := &JiangHuRenQuery{config: c.config}
	id := w.ID
	step := sqlgraph.NewStep(
		sqlgraph.From(weapon.Table, weapon.FieldID, id),
		sqlgraph.To(jianghuren.Table, jianghuren.FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, weapon.OwnerTable, weapon.OwnerColumn),
	)
	query.sql = sqlgraph.Neighbors(w.driver.Dialect(), step)

	return query
}

// Hooks returns the client hooks.
func (c *WeaponClient) Hooks() []Hook {
	return c.hooks.Weapon
}

// WuGongClient is a client for the WuGong schema.
type WuGongClient struct {
	config
}

// NewWuGongClient returns a client for the WuGong from the given config.
func NewWuGongClient(c config) *WuGongClient {
	return &WuGongClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `wugong.Hooks(f(g(h())))`.
func (c *WuGongClient) Use(hooks ...Hook) {
	c.hooks.WuGong = append(c.hooks.WuGong, hooks...)
}

// Create returns a create builder for WuGong.
func (c *WuGongClient) Create() *WuGongCreate {
	mutation := newWuGongMutation(c.config, OpCreate)
	return &WuGongCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for WuGong.
func (c *WuGongClient) Update() *WuGongUpdate {
	mutation := newWuGongMutation(c.config, OpUpdate)
	return &WuGongUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WuGongClient) UpdateOne(wg *WuGong) *WuGongUpdateOne {
	return c.UpdateOneID(wg.ID)
}

// UpdateOneID returns an update builder for the given id.
func (c *WuGongClient) UpdateOneID(id int) *WuGongUpdateOne {
	mutation := newWuGongMutation(c.config, OpUpdateOne)
	mutation.id = &id
	return &WuGongUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WuGong.
func (c *WuGongClient) Delete() *WuGongDelete {
	mutation := newWuGongMutation(c.config, OpDelete)
	return &WuGongDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *WuGongClient) DeleteOne(wg *WuGong) *WuGongDeleteOne {
	return c.DeleteOneID(wg.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *WuGongClient) DeleteOneID(id int) *WuGongDeleteOne {
	builder := c.Delete().Where(wugong.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WuGongDeleteOne{builder}
}

// Create returns a query builder for WuGong.
func (c *WuGongClient) Query() *WuGongQuery {
	return &WuGongQuery{config: c.config}
}

// Get returns a WuGong entity by its id.
func (c *WuGongClient) Get(ctx context.Context, id int) (*WuGong, error) {
	return c.Query().Where(wugong.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WuGongClient) GetX(ctx context.Context, id int) *WuGong {
	wg, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return wg
}

// Hooks returns the client hooks.
func (c *WuGongClient) Hooks() []Hook {
	return c.hooks.WuGong
}
