// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/BiLuoHui/ganshijiumei/ent/jianghuren"
	"github.com/BiLuoHui/ganshijiumei/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// JiangHuRenDelete is the builder for deleting a JiangHuRen entity.
type JiangHuRenDelete struct {
	config
	hooks      []Hook
	mutation   *JiangHuRenMutation
	predicates []predicate.JiangHuRen
}

// Where adds a new predicate to the delete builder.
func (jhrd *JiangHuRenDelete) Where(ps ...predicate.JiangHuRen) *JiangHuRenDelete {
	jhrd.predicates = append(jhrd.predicates, ps...)
	return jhrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (jhrd *JiangHuRenDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(jhrd.hooks) == 0 {
		affected, err = jhrd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*JiangHuRenMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			jhrd.mutation = mutation
			affected, err = jhrd.sqlExec(ctx)
			return affected, err
		})
		for i := len(jhrd.hooks) - 1; i >= 0; i-- {
			mut = jhrd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, jhrd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (jhrd *JiangHuRenDelete) ExecX(ctx context.Context) int {
	n, err := jhrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (jhrd *JiangHuRenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: jianghuren.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: jianghuren.FieldID,
			},
		},
	}
	if ps := jhrd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, jhrd.driver, _spec)
}

// JiangHuRenDeleteOne is the builder for deleting a single JiangHuRen entity.
type JiangHuRenDeleteOne struct {
	jhrd *JiangHuRenDelete
}

// Exec executes the deletion query.
func (jhrdo *JiangHuRenDeleteOne) Exec(ctx context.Context) error {
	n, err := jhrdo.jhrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{jianghuren.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (jhrdo *JiangHuRenDeleteOne) ExecX(ctx context.Context) {
	jhrdo.jhrd.ExecX(ctx)
}
