// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/BiLuoHui/ganshijiumei/ent/jianghuren"
	"github.com/facebookincubator/ent/dialect/sql"
)

// JiangHuRen is the model entity for the JiangHuRen schema.
type JiangHuRen struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Age holds the value of the "age" field.
	Age uint `json:"age,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JiangHuRen) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullTime{},   // created_at
		&sql.NullTime{},   // updated_at
		&sql.NullString{}, // name
		&sql.NullInt64{},  // age
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JiangHuRen fields.
func (jhr *JiangHuRen) assignValues(values ...interface{}) error {
	if m, n := len(values), len(jianghuren.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	jhr.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field created_at", values[0])
	} else if value.Valid {
		jhr.CreatedAt = value.Time
	}
	if value, ok := values[1].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field updated_at", values[1])
	} else if value.Valid {
		jhr.UpdatedAt = value.Time
	}
	if value, ok := values[2].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[2])
	} else if value.Valid {
		jhr.Name = value.String
	}
	if value, ok := values[3].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field age", values[3])
	} else if value.Valid {
		jhr.Age = uint(value.Int64)
	}
	return nil
}

// Update returns a builder for updating this JiangHuRen.
// Note that, you need to call JiangHuRen.Unwrap() before calling this method, if this JiangHuRen
// was returned from a transaction, and the transaction was committed or rolled back.
func (jhr *JiangHuRen) Update() *JiangHuRenUpdateOne {
	return (&JiangHuRenClient{config: jhr.config}).UpdateOne(jhr)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (jhr *JiangHuRen) Unwrap() *JiangHuRen {
	tx, ok := jhr.config.driver.(*txDriver)
	if !ok {
		panic("ent: JiangHuRen is not a transactional entity")
	}
	jhr.config.driver = tx.drv
	return jhr
}

// String implements the fmt.Stringer.
func (jhr *JiangHuRen) String() string {
	var builder strings.Builder
	builder.WriteString("JiangHuRen(")
	builder.WriteString(fmt.Sprintf("id=%v", jhr.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(jhr.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(jhr.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", name=")
	builder.WriteString(jhr.Name)
	builder.WriteString(", age=")
	builder.WriteString(fmt.Sprintf("%v", jhr.Age))
	builder.WriteByte(')')
	return builder.String()
}

// JiangHuRens is a parsable slice of JiangHuRen.
type JiangHuRens []*JiangHuRen

func (jhr JiangHuRens) config(cfg config) {
	for _i := range jhr {
		jhr[_i].config = cfg
	}
}
