// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/BiLuoHui/ganshijiumei/ent/menpai"
	"github.com/BiLuoHui/ganshijiumei/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// MenPaiDelete is the builder for deleting a MenPai entity.
type MenPaiDelete struct {
	config
	hooks      []Hook
	mutation   *MenPaiMutation
	predicates []predicate.MenPai
}

// Where adds a new predicate to the delete builder.
func (mpd *MenPaiDelete) Where(ps ...predicate.MenPai) *MenPaiDelete {
	mpd.predicates = append(mpd.predicates, ps...)
	return mpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mpd *MenPaiDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mpd.hooks) == 0 {
		affected, err = mpd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MenPaiMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mpd.mutation = mutation
			affected, err = mpd.sqlExec(ctx)
			return affected, err
		})
		for i := len(mpd.hooks) - 1; i >= 0; i-- {
			mut = mpd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mpd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpd *MenPaiDelete) ExecX(ctx context.Context) int {
	n, err := mpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mpd *MenPaiDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: menpai.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: menpai.FieldID,
			},
		},
	}
	if ps := mpd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mpd.driver, _spec)
}

// MenPaiDeleteOne is the builder for deleting a single MenPai entity.
type MenPaiDeleteOne struct {
	mpd *MenPaiDelete
}

// Exec executes the deletion query.
func (mpdo *MenPaiDeleteOne) Exec(ctx context.Context) error {
	n, err := mpdo.mpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{menpai.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mpdo *MenPaiDeleteOne) ExecX(ctx context.Context) {
	mpdo.mpd.ExecX(ctx)
}
