// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/BiLuoHui/ganshijiumei/ent/jianghuren"
	"github.com/BiLuoHui/ganshijiumei/ent/menpai"
	"github.com/BiLuoHui/ganshijiumei/ent/schema"
	"github.com/BiLuoHui/ganshijiumei/ent/weapon"
	"github.com/BiLuoHui/ganshijiumei/ent/wugong"

	"github.com/facebookincubator/ent"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	jianghurenMixin := schema.JiangHuRen{}.Mixin()
	jianghurenMixinFields := [...][]ent.Field{
		jianghurenMixin[0].Fields(),
	}
	jianghurenFields := schema.JiangHuRen{}.Fields()
	_ = jianghurenFields
	// jianghurenDescCreatedAt is the schema descriptor for created_at field.
	jianghurenDescCreatedAt := jianghurenMixinFields[0][0].Descriptor()
	// jianghuren.DefaultCreatedAt holds the default value on creation for the created_at field.
	jianghuren.DefaultCreatedAt = jianghurenDescCreatedAt.Default.(func() time.Time)
	// jianghurenDescUpdatedAt is the schema descriptor for updated_at field.
	jianghurenDescUpdatedAt := jianghurenMixinFields[0][1].Descriptor()
	// jianghuren.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	jianghuren.DefaultUpdatedAt = jianghurenDescUpdatedAt.Default.(func() time.Time)
	// jianghuren.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	jianghuren.UpdateDefaultUpdatedAt = jianghurenDescUpdatedAt.UpdateDefault.(func() time.Time)
	menpaiMixin := schema.MenPai{}.Mixin()
	menpaiMixinFields := [...][]ent.Field{
		menpaiMixin[0].Fields(),
	}
	menpaiFields := schema.MenPai{}.Fields()
	_ = menpaiFields
	// menpaiDescCreatedAt is the schema descriptor for created_at field.
	menpaiDescCreatedAt := menpaiMixinFields[0][0].Descriptor()
	// menpai.DefaultCreatedAt holds the default value on creation for the created_at field.
	menpai.DefaultCreatedAt = menpaiDescCreatedAt.Default.(func() time.Time)
	// menpaiDescUpdatedAt is the schema descriptor for updated_at field.
	menpaiDescUpdatedAt := menpaiMixinFields[0][1].Descriptor()
	// menpai.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	menpai.DefaultUpdatedAt = menpaiDescUpdatedAt.Default.(func() time.Time)
	// menpai.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	menpai.UpdateDefaultUpdatedAt = menpaiDescUpdatedAt.UpdateDefault.(func() time.Time)
	// menpaiDescAddress is the schema descriptor for address field.
	menpaiDescAddress := menpaiFields[1].Descriptor()
	// menpai.DefaultAddress holds the default value on creation for the address field.
	menpai.DefaultAddress = menpaiDescAddress.Default.(string)
	weaponMixin := schema.Weapon{}.Mixin()
	weaponMixinFields := [...][]ent.Field{
		weaponMixin[0].Fields(),
	}
	weaponFields := schema.Weapon{}.Fields()
	_ = weaponFields
	// weaponDescCreatedAt is the schema descriptor for created_at field.
	weaponDescCreatedAt := weaponMixinFields[0][0].Descriptor()
	// weapon.DefaultCreatedAt holds the default value on creation for the created_at field.
	weapon.DefaultCreatedAt = weaponDescCreatedAt.Default.(func() time.Time)
	// weaponDescUpdatedAt is the schema descriptor for updated_at field.
	weaponDescUpdatedAt := weaponMixinFields[0][1].Descriptor()
	// weapon.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	weapon.DefaultUpdatedAt = weaponDescUpdatedAt.Default.(func() time.Time)
	// weapon.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	weapon.UpdateDefaultUpdatedAt = weaponDescUpdatedAt.UpdateDefault.(func() time.Time)
	// weaponDescLevel is the schema descriptor for level field.
	weaponDescLevel := weaponFields[1].Descriptor()
	// weapon.DefaultLevel holds the default value on creation for the level field.
	weapon.DefaultLevel = weaponDescLevel.Default.(int)
	// weaponDescCategory is the schema descriptor for category field.
	weaponDescCategory := weaponFields[2].Descriptor()
	// weapon.DefaultCategory holds the default value on creation for the category field.
	weapon.DefaultCategory = weaponDescCategory.Default.(int)
	wugongMixin := schema.WuGong{}.Mixin()
	wugongMixinFields := [...][]ent.Field{
		wugongMixin[0].Fields(),
	}
	wugongFields := schema.WuGong{}.Fields()
	_ = wugongFields
	// wugongDescCreatedAt is the schema descriptor for created_at field.
	wugongDescCreatedAt := wugongMixinFields[0][0].Descriptor()
	// wugong.DefaultCreatedAt holds the default value on creation for the created_at field.
	wugong.DefaultCreatedAt = wugongDescCreatedAt.Default.(func() time.Time)
	// wugongDescUpdatedAt is the schema descriptor for updated_at field.
	wugongDescUpdatedAt := wugongMixinFields[0][1].Descriptor()
	// wugong.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	wugong.DefaultUpdatedAt = wugongDescUpdatedAt.Default.(func() time.Time)
	// wugong.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	wugong.UpdateDefaultUpdatedAt = wugongDescUpdatedAt.UpdateDefault.(func() time.Time)
	// wugongDescDamage is the schema descriptor for damage field.
	wugongDescDamage := wugongFields[1].Descriptor()
	// wugong.DefaultDamage holds the default value on creation for the damage field.
	wugong.DefaultDamage = wugongDescDamage.Default.(int)
	// wugongDescLevel is the schema descriptor for level field.
	wugongDescLevel := wugongFields[2].Descriptor()
	// wugong.LevelValidator is a validator for the "level" field. It is called by the builders before save.
	wugong.LevelValidator = wugongDescLevel.Validators[0].(func(uint8) error)
}
