// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/BiLuoHui/ganshijiumei/ent/jianghuren"
	"github.com/BiLuoHui/ganshijiumei/ent/menpai"
	"github.com/BiLuoHui/ganshijiumei/ent/schema"

	"github.com/facebookincubator/ent"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	jianghurenMixin := schema.JiangHuRen{}.Mixin()
	jianghurenMixinFields := [...][]ent.Field{
		jianghurenMixin[0].Fields(),
	}
	jianghurenFields := schema.JiangHuRen{}.Fields()
	_ = jianghurenFields
	// jianghurenDescCreatedAt is the schema descriptor for created_at field.
	jianghurenDescCreatedAt := jianghurenMixinFields[0][0].Descriptor()
	// jianghuren.DefaultCreatedAt holds the default value on creation for the created_at field.
	jianghuren.DefaultCreatedAt = jianghurenDescCreatedAt.Default.(func() time.Time)
	// jianghurenDescUpdatedAt is the schema descriptor for updated_at field.
	jianghurenDescUpdatedAt := jianghurenMixinFields[0][1].Descriptor()
	// jianghuren.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	jianghuren.DefaultUpdatedAt = jianghurenDescUpdatedAt.Default.(func() time.Time)
	// jianghuren.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	jianghuren.UpdateDefaultUpdatedAt = jianghurenDescUpdatedAt.UpdateDefault.(func() time.Time)
	menpaiMixin := schema.MenPai{}.Mixin()
	menpaiMixinFields := [...][]ent.Field{
		menpaiMixin[0].Fields(),
	}
	menpaiFields := schema.MenPai{}.Fields()
	_ = menpaiFields
	// menpaiDescCreatedAt is the schema descriptor for created_at field.
	menpaiDescCreatedAt := menpaiMixinFields[0][0].Descriptor()
	// menpai.DefaultCreatedAt holds the default value on creation for the created_at field.
	menpai.DefaultCreatedAt = menpaiDescCreatedAt.Default.(func() time.Time)
	// menpaiDescUpdatedAt is the schema descriptor for updated_at field.
	menpaiDescUpdatedAt := menpaiMixinFields[0][1].Descriptor()
	// menpai.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	menpai.DefaultUpdatedAt = menpaiDescUpdatedAt.Default.(func() time.Time)
	// menpai.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	menpai.UpdateDefaultUpdatedAt = menpaiDescUpdatedAt.UpdateDefault.(func() time.Time)
	// menpaiDescAddress is the schema descriptor for address field.
	menpaiDescAddress := menpaiFields[1].Descriptor()
	// menpai.DefaultAddress holds the default value on creation for the address field.
	menpai.DefaultAddress = menpaiDescAddress.Default.(string)
}
