// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/BiLuoHui/ganshijiumei/ent/wugong"
	"github.com/facebookincubator/ent/dialect/sql"
)

// WuGong is the model entity for the WuGong schema.
type WuGong struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Damage holds the value of the "damage" field.
	Damage int `json:"damage,omitempty"`
	// Level holds the value of the "level" field.
	Level uint8 `json:"level,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WuGong) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullTime{},   // created_at
		&sql.NullTime{},   // updated_at
		&sql.NullString{}, // name
		&sql.NullInt64{},  // damage
		&sql.NullInt64{},  // level
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WuGong fields.
func (wg *WuGong) assignValues(values ...interface{}) error {
	if m, n := len(values), len(wugong.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	wg.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field created_at", values[0])
	} else if value.Valid {
		wg.CreatedAt = value.Time
	}
	if value, ok := values[1].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field updated_at", values[1])
	} else if value.Valid {
		wg.UpdatedAt = value.Time
	}
	if value, ok := values[2].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[2])
	} else if value.Valid {
		wg.Name = value.String
	}
	if value, ok := values[3].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field damage", values[3])
	} else if value.Valid {
		wg.Damage = int(value.Int64)
	}
	if value, ok := values[4].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field level", values[4])
	} else if value.Valid {
		wg.Level = uint8(value.Int64)
	}
	return nil
}

// Update returns a builder for updating this WuGong.
// Note that, you need to call WuGong.Unwrap() before calling this method, if this WuGong
// was returned from a transaction, and the transaction was committed or rolled back.
func (wg *WuGong) Update() *WuGongUpdateOne {
	return (&WuGongClient{config: wg.config}).UpdateOne(wg)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (wg *WuGong) Unwrap() *WuGong {
	tx, ok := wg.config.driver.(*txDriver)
	if !ok {
		panic("ent: WuGong is not a transactional entity")
	}
	wg.config.driver = tx.drv
	return wg
}

// String implements the fmt.Stringer.
func (wg *WuGong) String() string {
	var builder strings.Builder
	builder.WriteString("WuGong(")
	builder.WriteString(fmt.Sprintf("id=%v", wg.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(wg.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(wg.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", name=")
	builder.WriteString(wg.Name)
	builder.WriteString(", damage=")
	builder.WriteString(fmt.Sprintf("%v", wg.Damage))
	builder.WriteString(", level=")
	builder.WriteString(fmt.Sprintf("%v", wg.Level))
	builder.WriteByte(')')
	return builder.String()
}

// WuGongs is a parsable slice of WuGong.
type WuGongs []*WuGong

func (wg WuGongs) config(cfg config) {
	for _i := range wg {
		wg[_i].config = cfg
	}
}
