// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/BiLuoHui/ganshijiumei/ent/predicate"
	"github.com/BiLuoHui/ganshijiumei/ent/wugong"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// WuGongDelete is the builder for deleting a WuGong entity.
type WuGongDelete struct {
	config
	hooks      []Hook
	mutation   *WuGongMutation
	predicates []predicate.WuGong
}

// Where adds a new predicate to the delete builder.
func (wgd *WuGongDelete) Where(ps ...predicate.WuGong) *WuGongDelete {
	wgd.predicates = append(wgd.predicates, ps...)
	return wgd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wgd *WuGongDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(wgd.hooks) == 0 {
		affected, err = wgd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WuGongMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wgd.mutation = mutation
			affected, err = wgd.sqlExec(ctx)
			return affected, err
		})
		for i := len(wgd.hooks) - 1; i >= 0; i-- {
			mut = wgd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wgd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (wgd *WuGongDelete) ExecX(ctx context.Context) int {
	n, err := wgd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wgd *WuGongDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: wugong.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: wugong.FieldID,
			},
		},
	}
	if ps := wgd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, wgd.driver, _spec)
}

// WuGongDeleteOne is the builder for deleting a single WuGong entity.
type WuGongDeleteOne struct {
	wgd *WuGongDelete
}

// Exec executes the deletion query.
func (wgdo *WuGongDeleteOne) Exec(ctx context.Context) error {
	n, err := wgdo.wgd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{wugong.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wgdo *WuGongDeleteOne) ExecX(ctx context.Context) {
	wgdo.wgd.ExecX(ctx)
}
