// Code generated by entc, DO NOT EDIT.

package jianghuren

import (
	"time"
)

const (
	// Label holds the string label denoting the jianghuren type in the database.
	Label = "jiang_hu_ren"
	// FieldID holds the string denoting the id field in the database.
	FieldID        = "id"         // FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt = "created_at" // FieldUpdatedAt holds the string denoting the updated_at vertex property in the database.
	FieldUpdatedAt = "updated_at" // FieldName holds the string denoting the name vertex property in the database.
	FieldName      = "name"       // FieldAge holds the string denoting the age vertex property in the database.
	FieldAge       = "age"

	// Table holds the table name of the jianghuren in the database.
	Table = "jiang_hu_rens"
)

// Columns holds all SQL columns for jianghuren fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldAge,
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	UpdateDefaultUpdatedAt func() time.Time
)
