// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// JiangHuRen is the predicate function for jianghuren builders.
type JiangHuRen func(*sql.Selector)

// MenPai is the predicate function for menpai builders.
type MenPai func(*sql.Selector)

// Weapon is the predicate function for weapon builders.
type Weapon func(*sql.Selector)

// WuGong is the predicate function for wugong builders.
type WuGong func(*sql.Selector)
