// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// JiangHuRen is the predicate function for jianghuren builders.
type JiangHuRen func(*sql.Selector)

// MenPai is the predicate function for menpai builders.
type MenPai func(*sql.Selector)
